# Generated by Django 2.2 on 2020-09-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_auto_20200623_1442"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription", old_name="name", new_name="first_name",
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
