# Generated by Django 2.2 on 2021-01-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_auto_20200916_0730"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="accepted_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
